### ISSUE TITLE
Allow npm install of spago@next

### ISSUE THREAD

**Issue by natefaubion** [purescript-contrib/setup-purescript#37]
Currently spago is hardcoded to use github releases for legacy spago. Would it be possible to use npm for install for spago next/unstable?

**Comment by natefaubion** [comment]
Current workaround is to install spago in a step using npm and invoke from `node_modules/.bin` or `npx`.

**Comment by thomashoneyman** [comment]
Yes, we would need to update this:

https://github.com/purescript-contrib/setup-purescript/blob/b05977681dde855924b5e4805bd292b53acf4c0a/src/Setup/Data/Tool.purs#L118-L133

...such that if the Spago version is greater than 0.90.x then we use NPM as the installation method.

**Comment by thomashoneyman** [comment]
We would also need to update the get latest versions script so that it looks at NPM releases for Spago; right now everything looks at GitHub releases, but the spago@next releases are not happening on GitHub releases at all.

https://github.com/purescript-contrib/setup-purescript/blob/b05977681dde855924b5e4805bd292b53acf4c0a/src/Setup/UpdateVersions.purs#L74
